# Don't print a new line at the start of the prompt
add_newline = false

# Overwrite a default_prompt_order and  use custom prompt_order
#format = """
#$directory\
#$git_branch\
#$git_state\
#$git_status\
#$kubernetes\
#$line_break\
#$character\
#"""

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
#disabled = true

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ""

[kubernetes]
disabled = false

[golang]
symbol = "GO "

[python]
format = 'via [${symbol}${pyenv_prefix}($virtualenv)]($style) '
symbol = ""
pyenv_version_name = true

[aws]
style = "bold blue"
symbol = "AWS "
displayed_items = "all"

[aws.region_aliases]
ap-northeast-1 = "jp"
