# Don't print a new line at the start of the prompt
add_newline = false

# Overwrite a default_prompt_order and  use custom prompt_order
prompt_order= [
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "kubernetes",
    "line_break",
    "character",
]

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
#disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false

[kubernetes]
disabled = false

[git_branch]
symbol = ""
